server:
  port:
    8761

spring:
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: http://localhost:8080/
          predicates:
            - Path=/authentication/**
        - id: management
          uri: http://localhost:8081/
          predicates:
            - Path=/management/**