image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

management-build:
  stage: build
  script:
    gradle :management:build

management-checkStyle:
  stage: staticAnalysis
  script:
    gradle :management:checkstyleMain :management:checkStyleTest

management-PMD:
  stage: staticAnalysis
  script:
      gradle :management:pmdMain :management:pmdTest

management-test:
  stage: test
  script:
    gradle :management:test :management:jacocoTestReport
  coverage: /([0-9]{1,3})%/

