image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

management-build:
  stage: build
  script:
    gradle build

management-checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkStyleTest

management-PMD:
  stage: staticAnalysis
  script:
      gradle pmdMain pmdTest

management-test:
  stage: test
  script:
    gradle test
