image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

student-build:
  stage: build
  script:
    gradle :student:build

student-checkStyle:
  stage: staticAnalysis
  script:
    gradle :student:checkstyleMain :student:checkStyleTest

student-PMD:
  stage: staticAnalysis
  script:
      gradle :student:pmdMain :student:pmdTest

student-test:
  stage: test
  script:
    gradle :student:test
