image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

lecturer-build:
  stage: build
  script:
    gradle :lecturer:build

lecturer-checkStyle:
  stage: staticAnalysis
  script:
    gradle :lecturer:checkstyleMain :lecturer:checkStyleTest

lecturer-PMD:
  stage: staticAnalysis
  script:
      gradle :lecturer:pmdMain :lecturer:pmdTest

lecturer-test:
  stage: test
  script:
    gradle :lecturer:test
