image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

course-build:
  stage: build
  script:
    gradle :course:build

course-checkStyle:
  stage: staticAnalysis
  script:
    gradle :course:checkstyleMain :course:checkStyleTest

course-PMD:
  stage: staticAnalysis
  script:
      gradle :course:pmdMain :course:pmdTest

course-test:
  stage: test
  script:
    gradle :course:test
