image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

authentication-build:
  stage: build
  script:
    gradle :authentication:build

authentication-checkStyle:
  stage: staticAnalysis
  script:
    gradle :authentication:checkstyleMain :authentication:checkStyleTest

authentication-PMD:
  stage: staticAnalysis
  script:
      gradle :authentication:pmdMain :authentication:pmdTest

authentication-test:
  stage: test
  script:
    gradle :authentication:test
