image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

authentication-build:
  stage: build
  script:
    gradle build

authentication-checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkStyleTest

authentication-PMD:
  stage: staticAnalysis
  script:
      gradle pmdMain pmdTest

authentication-test:
  stage: test
  script:
    gradle test
